export const activitiesData = [
  {
    id: 1,
    title: "مؤتمر الفنون المعاصرة في الشرق الأوسط",
    description: "مؤتمر دولي يجمع نخبة من الفنانين والنقاد لمناقشة مستقبل الفنون المعاصرة في المنطقة",
    image: "/placeholder.svg?height=300&width=400",
    date: "15-17 يونيو 2025",
    location: "مركز أبو ظبي للمؤتمرات",
    category: "مؤتمرات",
    attendees: "200+ مشارك",
    status: "قادم",
  },
  {
    id: 2,
    title: "معرض الفن الإسلامي المعاصر",
    description: "معرض يستكشف تطور الفن الإسلامي في العصر الحديث ويعرض أعمال فنانين من مختلف البلدان الإسلامية",
    image: "/placeholder.svg?height=300&width=400",
    date: "20 يونيو - 30 يوليو 2025",
    location: "قاعة المعارض الكبرى",
    category: "معارض",
    attendees: "مفتوح للجمهور",
    status: "قادم",
  },
  {
    id: 3,
    title: "ورشة الخط العربي للمبتدئين",
    description: "ورشة تعليمية مكثفة لتعلم أساسيات الخط العربي وجمالياته مع خطاطين محترفين",
    image: "/placeholder.svg?height=300&width=400",
    date: "25-27 يونيو 2025",
    location: "مركز التدريب",
    category: "ورش عمل",
    attendees: "30 مشارك",
    status: "التسجيل مفتوح",
  },
  {
    id: 4,
    title: "أمسية شعرية بعنوان 'كلمات من الإمارات'",
    description: "أمسية شعرية تحتفي بالشعر الإماراتي المعاصر بمشاركة نخبة من الشعراء المحليين",
    image: "/placeholder.svg?height=300&width=400",
    date: "5 يوليو 2025",
    location: "مسرح أبوظبي الثقافي",
    category: "أمسيات",
    attendees: "500 مقعد",
    status: "قادم",
  },
  {
    id: 5,
    title: "ندوة 'الذكاء الاصطناعي والفنون'",
    description: "ندوة تناقش تأثير التكنولوجيا والذكاء الاصطناعي على مستقبل الفنون والإبداع",
    image: "/placeholder.svg?height=300&width=400",
    date: "10 يوليو 2025",
    location: "قاعة المؤتمرات",
    category: "ندوات",
    attendees: "150 مشارك",
    status: "قادم",
  },
  {
    id: 6,
    title: "مهرجان الأفلام الوثائقية العربية",
    description: "مهرجان سينمائي يعرض أفضل الأفلام الوثائقية العربية المعاصرة",
    image: "/placeholder.svg?height=300&width=400",
    date: "15-20 يوليو 2025",
    location: "سينما أبوظبي",
    category: "مهرجانات",
    attendees: "مفتوح للجمهور",
    status: "قادم",
  },
] 